//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki.Ressource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RessourceView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RessourceView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wiki.Ressource.RessourceView", typeof(RessourceView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu.
        /// </summary>
        public static string Contenu {
            get {
                return ResourceManager.GetString("Contenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de modification.
        /// </summary>
        public static string DateModification {
            get {
                return ResourceManager.GetString("DateModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id  Contributeur.
        /// </summary>
        public static string IdContributeur {
            get {
                return ResourceManager.GetString("IdContributeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. de revision.
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apercu Contenu Html.
        /// </summary>
        public static string vHC_Ajout_apercuContHtml {
            get {
                return ResourceManager.GetString("vHC_Ajout_apercuContHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apercu Html.
        /// </summary>
        public static string vHC_Ajout_apercuHtml {
            get {
                return ResourceManager.GetString("vHC_Ajout_apercuHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string vHC_erreur_erruer {
            get {
                return ResourceManager.GetString("vHC_erreur_erruer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite lors du traitement de votre demande..
        /// </summary>
        public static string vHC_erreur_phrase {
            get {
                return ResourceManager.GetString("vHC_erreur_phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article inexistant!.
        /// </summary>
        public static string vHC_Ind_articleNull {
            get {
                return ResourceManager.GetString("vHC_Ind_articleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue au Wiki!.
        /// </summary>
        public static string vHC_Ind_bienvenu {
            get {
                return ResourceManager.GetString("vHC_Ind_bienvenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer cet article.
        /// </summary>
        public static string vHC_Ind_creerArticle {
            get {
                return ResourceManager.GetString("vHC_Ind_creerArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souhaitez-vous créer l&apos;article.
        /// </summary>
        public static string vHC_Ind_SouhaitCreArticle {
            get {
                return ResourceManager.GetString("vHC_Ind_SouhaitCreArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails Article.
        /// </summary>
        public static string vHC_partDet_artDetail {
            get {
                return ResourceManager.GetString("vHC_partDet_artDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table des Matières.
        /// </summary>
        public static string vHC_partTabMat_tabMatier {
            get {
                return ResourceManager.GetString("vHC_partTabMat_tabMatier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous certain de vouloir supprimer l&apos;article?.
        /// </summary>
        public static string vHC_supprim_quest {
            get {
                return ResourceManager.GetString("vHC_supprim_quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string ZHC_ajout {
            get {
                return ResourceManager.GetString("ZHC_ajout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string ZHC_article {
            get {
                return ResourceManager.GetString("ZHC_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string ZHC_enregist {
            get {
                return ResourceManager.GetString("ZHC_enregist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string ZHC_menu_conn {
            get {
                return ResourceManager.GetString("ZHC_menu_conn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deconnexion.
        /// </summary>
        public static string ZHC_menu_dec {
            get {
                return ResourceManager.GetString("ZHC_menu_dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription.
        /// </summary>
        public static string ZHC_menu_ins {
            get {
                return ResourceManager.GetString("ZHC_menu_ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string ZHC_menu_prof {
            get {
                return ResourceManager.GetString("ZHC_menu_prof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string ZHC_modif {
            get {
                return ResourceManager.GetString("ZHC_modif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour page précédente.
        /// </summary>
        public static string ZHC_Modif_retourPreced {
            get {
                return ResourceManager.GetString("ZHC_Modif_retourPreced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à l&apos;Accueuil.
        /// </summary>
        public static string ZHC_retourAcc {
            get {
                return ResourceManager.GetString("ZHC_retourAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string ZHC_suprim {
            get {
                return ResourceManager.GetString("ZHC_suprim", resourceCulture);
            }
        }
    }
}
