//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki.Ressource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RessourceView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RessourceView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wiki.Ressource.RessourceView", typeof(RessourceView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Contenu {
            get {
                return ResourceManager.GetString("Contenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string courriel {
            get {
                return ResourceManager.GetString("courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DateModification {
            get {
                return ResourceManager.GetString("DateModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ERR_courriel {
            get {
                return ResourceManager.GetString("ERR_courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ERR_courriel_invalide {
            get {
                return ResourceManager.GetString("ERR_courriel_invalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ERR_courriel50 {
            get {
                return ResourceManager.GetString("ERR_courriel50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ERR_dejaExist {
            get {
                return ResourceManager.GetString("ERR_dejaExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ERR_HC_Home_titre {
            get {
                return ResourceManager.GetString("ERR_HC_Home_titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ERR_MDP {
            get {
                return ResourceManager.GetString("ERR_MDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ERR_MDP_entree {
            get {
                return ResourceManager.GetString("ERR_MDP_entree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ERR_MDPCompare {
            get {
                return ResourceManager.GetString("ERR_MDPCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ERR_nom {
            get {
                return ResourceManager.GetString("ERR_nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ERR_nom50 {
            get {
                return ResourceManager.GetString("ERR_nom50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ERR_prenom {
            get {
                return ResourceManager.GetString("ERR_prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ERR_prenom50 {
            get {
                return ResourceManager.GetString("ERR_prenom50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GO {
            get {
                return ResourceManager.GetString("GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IdContributeur {
            get {
                return ResourceManager.GetString("IdContributeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string langue {
            get {
                return ResourceManager.GetString("langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MDPConfirmer {
            get {
                return ResourceManager.GetString("MDPConfirmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string motDePass {
            get {
                return ResourceManager.GetString("motDePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string motDePassConfirm {
            get {
                return ResourceManager.GetString("motDePassConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string nomFamille {
            get {
                return ResourceManager.GetString("nomFamille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string nouvMotDePass {
            get {
                return ResourceManager.GetString("nouvMotDePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string prenom {
            get {
                return ResourceManager.GetString("prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vHC_Ajout_apercuContHtml {
            get {
                return ResourceManager.GetString("vHC_Ajout_apercuContHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vHC_Ajout_apercuHtml {
            get {
                return ResourceManager.GetString("vHC_Ajout_apercuHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vHC_erreur_erruer {
            get {
                return ResourceManager.GetString("vHC_erreur_erruer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vHC_erreur_phrase {
            get {
                return ResourceManager.GetString("vHC_erreur_phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vHC_Ind_articleNull {
            get {
                return ResourceManager.GetString("vHC_Ind_articleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vHC_Ind_bienvenu {
            get {
                return ResourceManager.GetString("vHC_Ind_bienvenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vHC_Ind_creerArticle {
            get {
                return ResourceManager.GetString("vHC_Ind_creerArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vHC_Ind_placeHolder {
            get {
                return ResourceManager.GetString("vHC_Ind_placeHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vHC_Ind_SouhaitCreArticle {
            get {
                return ResourceManager.GetString("vHC_Ind_SouhaitCreArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vHC_partDet_artDetail {
            get {
                return ResourceManager.GetString("vHC_partDet_artDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vHC_partTabMat_tabMatier {
            get {
                return ResourceManager.GetString("vHC_partTabMat_tabMatier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vHC_supprim_quest {
            get {
                return ResourceManager.GetString("vHC_supprim_quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_ajout {
            get {
                return ResourceManager.GetString("ZHC_ajout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_article {
            get {
                return ResourceManager.GetString("ZHC_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_connexion_compte {
            get {
                return ResourceManager.GetString("ZHC_connexion_compte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_enregist {
            get {
                return ResourceManager.GetString("ZHC_enregist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_lang_en {
            get {
                return ResourceManager.GetString("ZHC_lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_lang_es {
            get {
                return ResourceManager.GetString("ZHC_lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_lang_fr {
            get {
                return ResourceManager.GetString("ZHC_lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_menu_conn {
            get {
                return ResourceManager.GetString("ZHC_menu_conn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_menu_dec {
            get {
                return ResourceManager.GetString("ZHC_menu_dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_menu_ins {
            get {
                return ResourceManager.GetString("ZHC_menu_ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_menu_langue {
            get {
                return ResourceManager.GetString("ZHC_menu_langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_menu_prof {
            get {
                return ResourceManager.GetString("ZHC_menu_prof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_modif {
            get {
                return ResourceManager.GetString("ZHC_modif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_Modif_retourPreced {
            get {
                return ResourceManager.GetString("ZHC_Modif_retourPreced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_modifMDP_backtolist {
            get {
                return ResourceManager.GetString("ZHC_modifMDP_backtolist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_modifProfil {
            get {
                return ResourceManager.GetString("ZHC_modifProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_mProfil_modifMDP {
            get {
                return ResourceManager.GetString("ZHC_mProfil_modifMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_retourAcc {
            get {
                return ResourceManager.GetString("ZHC_retourAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ZHC_suprim {
            get {
                return ResourceManager.GetString("ZHC_suprim", resourceCulture);
            }
        }
    }
}
